#!/bin/sh
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...

ln -sf /var/packages/dlcardPkg/target/nginx-conf/www.dlcard.disabled.conf /usr/local/etc/nginx/conf.d/

exit 0
