#!/bin/sh
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

case $1 in
	start)
		### Start this package.
		rm -rf /usr/local/etc/nginx/conf.d/www.dlcard.disabled.conf
		ln -sf /var/packages/dlcardPkg/target/nginx-conf/www.dlcard.enable.conf /usr/local/etc/nginx/conf.d/
		exit 0
	;;
	stop)
		### Stop this package.
		rm -rf /usr/local/etc/nginx/conf.d/www.dlcard.enable.conf
		ln -sf /var/packages/dlcardPkg/target/nginx-conf/www.dlcard.disabled.conf /usr/local/etc/nginx/conf.d/
		exit 0
	;;
	status)
		### Check package alive.
		if [ -h "/usr/local/etc/nginx/conf.d/www.dlcard.enable.conf" ]; then
			exit 0
		else
			exit 1
		fi
	;;
	killall)
        ;;
	log)
		exit 0
	;;
esac

